name: Process YAML files and create release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  processs-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download script from gist
      run: curl -o build_addons.py https://gist.githubusercontent.com/ProjectInfinity/9730b5080ff0326488e5cffbac263d27/raw/e72d22b88d72de5269debc0c31a41658b6a0463b/build_addons.py

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Build addons.json
      run: python build_addons.py

    - name: Get the short commit SHA
      id: get_commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: "release-${{ env.sha }}"
        release_name: 'Latest addons'
        body: 'Please contact Sami with any issues'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload addons.json to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: addons.json
        asset_name: addons.json
        asset_content_type: application/json
