name: Process YAML files and create release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  processs-yaml:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyyaml

    - name: Build addons.json
      run: python .github/build_addons.py

    - name: Get the short commit SHA
      id: get_commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create a release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: addons.json
        tag_name: ${{ env.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
